### ISSUE TITLE
Template file not found due to use of quotes around multiple template file paths

### ISSUE THREAD

**Issue by jmeridth** [shogo82148/actions-cfn-lint#187]
```bash
Run shogo82148/actions-cfn-lint@v1
  with:
    github_token: ***
    args: **/*.yaml *.json
    level: error
    tool_name: cfn-lint
    reporter: github-pr-check
    filter_mode: added
    fail_on_error: false
/usr/bin/docker run --name shogo82148actionscfnlint1614_a00229 --label 5588e4 --workdir /github/workspace --rm -e INPUT_GITHUB_TOKEN -e INPUT_ARGS -e INPUT_LEVEL -e INPUT_TOOL_NAME -e INPUT_REPORTER -e INPUT_FILTER_MODE -e INPUT_FAIL_ON_ERROR -e INPUT_REVIEWDOG_FLAGS -e HOME -e GITHUB_JOB -e GITHUB_REF -e GITHUB_SHA -e GITHUB_REPOSITORY -e GITHUB_REPOSITORY_OWNER -e GITHUB_RUN_ID -e GITHUB_RUN_NUMBER -e GITHUB_RETENTION_DAYS -e GITHUB_ACTOR -e GITHUB_WORKFLOW -e GITHUB_HEAD_REF -e GITHUB_BASE_REF -e GITHUB_EVENT_NAME -e GITHUB_SERVER_URL -e GITHUB_API_URL -e GITHUB_GRAPHQL_URL -e GITHUB_WORKSPACE -e GITHUB_ACTION -e GITHUB_EVENT_PATH -e GITHUB_ACTION_REPOSITORY -e GITHUB_ACTION_REF -e GITHUB_PATH -e GITHUB_ENV -e RUNNER_OS -e RUNNER_TOOL_CACHE -e RUNNER_TEMP -e RUNNER_WORKSPACE -e ACTIONS_RUNTIME_URL -e ACTIONS_RUNTIME_TOKEN -e ACTIONS_CACHE_URL -e GITHUB_ACTIONS=true -e CI=true -v "/var/run/docker.sock":"/var/run/docker.sock" -v "/home/runner/work/_temp/_github_home":"/github/home" -v "/home/runner/work/_temp/_github_workflow":"/github/workflow" -v "/home/runner/work/_temp/_runner_file_commands":"/github/file_commands" -v "/home/runner/work/REDACTED_REPO_NAME/REDACTED_REPO_NAME":"/github/workspace" shogo82148/actions-cfn-lint:1.6.14  "**/*.yaml" "**/*.yml" "**/*.json"
2021-02-19 19:08:47,893 - cfnlint.decode - ERROR - Template file not found: **/*.yaml
2021-02-19 19:08:47,893 - cfnlint.decode - ERROR - Template file not found: *.json
reviewdog: failed to run 'git rev-parse --show-prefix': exit status 128
```

Receive error above with this github action configuration:

```yaml
name: Pull Request
on:
  pull_request:

jobs:
  Lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Cloudformation template linting
        uses: shogo82148/actions-cfn-lint@v1
        with:
          github_token: ${{ secrets.REDACTED_TOKEN_KEY }}
          args: "**/*.yaml *.json"
```

I have `.json` files in the root of our repo and we have subfolders with the cloudformation yaml files.  When I run the command line tool `cfn-lint` directly I get the same error above when I use quotes (single or double)

DOUBLE QUOTES

```bash
$ cfn-lint "**/*.yaml *.json"
2021-02-19 13:29:33,790 - cfnlint.decode - ERROR - Template file not found: **/*.yaml *.json
E0000 Template file not found: **/*.yaml *.json
**/*.yaml *.json:1:1
```

SINGLE QUOTES

```bash
$ cfn-lint '**/*.yaml *.json'
2021-02-19 13:29:38,405 - cfnlint.decode - ERROR - Template file not found: **/*.yaml *.json
E0000 Template file not found: **/*.yaml *.json
**/*.yaml *.json:1:1
```

USE `--template` in quotes

```bash
$ cfn-lint "--template **/*.yaml *.json"
2021-02-19 13:35:47,163 - cfnlint.decode - ERROR - Template file not found: --template **/*.yaml *.json
E0000 Template file not found: --template **/*.yaml *.json
--template **/*.yaml *.json:1:1
```

**When I don't use quotes with the cli tool it runs as expected**

I understand yaml doesn't like me leaving it like this:

```yaml
args: **/*.yaml *.json
```

Errors with this:

![Screen Shot 2021-02-19 at 1 33 07 PM](https://user-images.githubusercontent.com/35014/108552506-04cc1f80-72b7-11eb-8d63-391ef1519e4e.png)

Suggestion:
Turn this into an array so that I can do

```yaml
args:
  - "**/*.yaml"
  - "*.json"
```

or something else.

Have any ideas that I may just be missing or would you like a PR?

Thank you.

**Comment by jmeridth** [comment]
If I'm doing my research correctly, it looks like arrays aren't supported.  But json string arrays are.  [Example](https://github.com/s4u/maven-settings-action/blob/master/action.yml#L34-L36). But that will definitely complicate things. 🤔

**Comment by jmeridth** [comment]
Decided to go the config file route

```yaml
name: Pull Request
on:
  pull_request:

jobs:
  Lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Cloudformation template linting
        uses: shogo82148/actions-cfn-lint@v1
        with:
          github_token: ${{ secrets. REDACTED_TOKEN_KEY }}
          args: --config-file .cfnlintrc
```

`.cfnlintrc`

```
templates:
  - "**/*.yaml"
  - "*.json"
```

Error I'm seeing when the workflow runs is

```bash
2021-02-20 19:42:55,719 - cfnlint.decode - ERROR - Template file not found: None
reviewdog: failed to run 'git rev-parse --show-prefix': exit status 128
```

Running the CLI locally with the following works

```bash
cfn-lint --config-file .cfnlintrc
```

Any ideas?

Thank you.

**Comment by shogo82148** [comment]
Thank you for your repot.

> Suggestion:
> Turn this into an array so that I can do
> 
> ```yaml
> args:
>   - "**/*.yaml"
>   - "*.json"
> ```
> 

It works in `actions.yaml`.
https://github.com/shogo82148/actions-cfn-lint/blob/790081de60aaebbd43d4106eb037e2bebb09a80b/action.yml#L43-L46

but unfortunately, it doesn't work in `.github/workflows`.
`.github/workflows` only accepts string values.

> Decided to go the config file route
> 
> ```
> name: Pull Request
> on:
>   pull_request:
> 
> jobs:
>   Lint:
>     name: Lint
>     runs-on: ubuntu-latest
>     steps:
>       - name: Cloudformation template linting
>         uses: shogo82148/actions-cfn-lint@v1
>         with:
>           github_token: ${{ secrets. REDACTED_TOKEN_KEY }}
>           args: --config-file .cfnlintrc
> ```
> 

This workflow will execute the following command.

```
cfn-lint "--config-file .cfnlintrc"
```

hmm... 🤔

**Comment by shogo82148** [comment]
I just published https://github.com/shogo82148/actions-cfn-lint/pull/188 as v1.6.15-beta1.
I added new parameter `cfn_lint_args`.

```
cfn_lint_args: --config-file .cfnlintrc
```

Can you try it please?

**Comment by jmeridth** [comment]
Still not working for me

My github action:

```yaml
name: Pull Request
on:
  pull_request:

jobs:
  Lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Cloudformation template linting
        uses: shogo82148/actions-cfn-lint@1a52aa373ac920e927fafe2ddf0504ad6d167662
        with:
          github_token: ${{ secrets.REDACTED_TOKEN_KEY}}
          cfn_lint_args: --config-file .cfnlintrc
```

My `.cfnlintrc` file contents:

```bash
templates:
  - "**/*.yaml"
  - "*.json"
 
```

**Result:**

```bash
Run shogo82148/actions-cfn-lint@1a52aa373ac920e927fafe2ddf0504ad6d167662
  with:
    github_token: ***
    cfn_lint_args: --config-file .cfnlintrc
    level: error
    tool_name: cfn-lint
    reporter: github-pr-check
    filter_mode: added
    fail_on_error: false
.....
2021-02-21 18:02:51,047 - cfnlint.decode - ERROR - Template file not found: **/*.json
2021-02-21 18:02:51,048 - cfnlint.decode - ERROR - Template file not found: **/*.yaml
2021-02-21 18:02:51,048 - cfnlint.decode - ERROR - Template file not found: **/*.yml
reviewdog: failed to run 'git rev-parse --show-prefix': exit status 128
```

I even tried `cfn_lint_args: --config-file $GITHUB_WORKSPACE/.cfnlintrc` in case it was a pathing issue.  Same error as above

Note: I learned we can't access/pull patch or beta versions.  Have to reference SHA directly, hence the `shogo82148/actions-cfn-lint@1a52aa373ac920e927fafe2ddf0504ad6d167662`.  Learned that from [here](https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions#jobsjob_idstepsuses).  Sharing in case you didn't know.

Thank you very much for working with me on this.  Cheers.

**Comment by jmeridth** [comment]
@shogo82148 I see why.  You didn't include you `entrypoint.sh` change from [here](https://github.com/shogo82148/actions-cfn-lint/pull/188/files#diff-6f9d41d046756f0ddc2fcee0626bdb50100d12b88f293734eff742818e03efa2R5-R7) in your [commit](https://github.com/shogo82148/actions-cfn-lint/commit/1a52aa373ac920e927fafe2ddf0504ad6d167662) with the new version.  Just need that `entrypoint.sh` change for it to pay attention to my `cfn_lint_args` 😄

**Comment by shogo82148** [comment]
oops, I fixed it and released it as v1.6.15-beta2

**Comment by jmeridth** [comment]
So it seems when I used the SHA it was still pulling 1.6.14 image.  But when I use `1.6.15-beta2` I get the following error:

```bash
Current runner version: '2.277.1'
Operating System
Virtual Environment
GITHUB_TOKEN Permissions
Prepare workflow directory
Prepare all required actions
Getting action download info
Failed to resolve action download info. Error: Unable to resolve action `shogo82148/actions-cfn-lint@1.6.15-beta2`, unable to find version `1.6.15-beta2`
Retrying in 17.048 seconds
Failed to resolve action download info. Error: Unable to resolve action `shogo82148/actions-cfn-lint@1.6.15-beta2`, unable to find version `1.6.15-beta2`
Retrying in 12.646 seconds
Error: Unable to resolve action `shogo82148/actions-cfn-lint@1.6.15-beta2`, unable to find version `1.6.15-beta2`
```

I see you have the tag and release on your github repository and I see the docker image available on docker hub [here](https://hub.docker.com/layers/shogo82148/actions-cfn-lint/1.6.15-beta2/images/sha256-ad5f384b2edfbfda9b4cf926a73cb1aefc6ab5dfb6d83e90b690edba199eb7df?context=explore).  Github caching issues maybe?

When I changed the `uses` statement in my github action to this

```yaml
uses: docker://shogo82148/actions-cfn-lint:1.6.15-beta2
```

it finally pulled from docker hub. but I got an error about reviewdog input.

```bash
Run docker://shogo82148/actions-cfn-lint:1.6.15-beta2
  with:
    github_token: ***
    cfn_lint_args: --config-file .cfnlintrc
...
2021-02-22 02:55:01,812 - cfnlint.decode - ERROR - Template file not found: None
invalid boolean value "" for -fail-on-error: parse error
Usage:	reviewdog [flags]
```

I did notice the with block previously used the defaults like so

```bash
Run shogo82148/actions-cfn-lint@1a52aa373ac920e927fafe2ddf0504ad6d167662
  with:
    github_token: ***
    cfn_lint_args: --config-file $GITHUB_WORKSPACE/.cfnlintrc
    level: error
    tool_name: cfn-lint
    reporter: github-pr-check
    filter_mode: added
    fail_on_error: false
```

but this run with docker hub only had the items I used in my github action

```bash
Run docker://shogo82148/actions-cfn-lint:1.6.15-beta2
  with:
    github_token: ***
    cfn_lint_args: --config-file .cfnlintrc
```

Don't know what that is about yet.  Looks like the defaults aren't being set.  I can set them in my github action for now as a workaround.  Any ideas?

Thank you again for working through this with me.

Cheers.

**Comment by jmeridth** [comment]
I'm going to assume it is because if the env variables aren't set by Github Actions they can't be used in `entrypoint.sh` [here](https://github.com/shogo82148/actions-cfn-lint/blob/main/entrypoint.sh#L15-L19).  Hence why it thinks it received an empty string for `INPUT_FAIL_ON_ERROR` instead of a boolean.

I don't know default boolean in bash (maybe 1 or 0) but the notation I've used in the past is `${VARIABLE:-default}` so `${INPUT_FAIL_ON_ERROR:-0}` maybe?

**Comment by jmeridth** [comment]
Tried the normal (non docker hub) notation again to no avail.  I don't know why this isn't working

```bash
Current runner version: '2.277.1'
Operating System
Virtual Environment
GITHUB_TOKEN Permissions
Prepare workflow directory
Prepare all required actions
Getting action download info
Failed to resolve action download info. Error: Unable to resolve action `shogo82148/actions-cfn-lint@1.6.15-beta2`, unable to find version `1.6.15-beta2`
Retrying in 10.469 seconds
Failed to resolve action download info. Error: Unable to resolve action `shogo82148/actions-cfn-lint@1.6.15-beta2`, unable to find version `1.6.15-beta2`
Retrying in 12.038 seconds
Error: Unable to resolve action `shogo82148/actions-cfn-lint@1.6.15-beta2`, unable to find version `1.6.15-beta2`
```

**Comment by jmeridth** [comment]
When I changed the uses statement in my github action to this

```yaml
uses: shogo82148/actions-cfn-lint@main
```

It pulls the old 1.6.14 docker hub image.  

```bash
Pull down action image 'shogo82148/actions-cfn-lint:1.6.14'
```

is that because of [this](https://github.com/shogo82148/actions-cfn-lint/blob/main/action.yml#L42)?

Based on [these docs](https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions#jobsjob_idstepsuses) I thought using `@main` would work.  Guess not.

**Comment by jmeridth** [comment]
SMH (shaking my head)

I just realized why my previous attempts were failing.  I was missing the `v` prefix on the version.  Needed to be `v1.6.15-beta2` instead of `1.6.15-beta2`

After updating to 

```yaml
 uses: shogo82148/actions-cfn-lint@v1.6.15-beta2
```

It is still trying to pull the `1.6.14` docker image like I mention in previous comment.  I think it is because of [this](https://github.com/shogo82148/actions-cfn-lint/blob/main/action.yml#L42).  I might be wrong.

**Comment by shogo82148** [comment]
please try it

```yaml
uses: shogo82148/actions-cfn-lint@v1.6.15-beta3
```

**Comment by jmeridth** [comment]
Still erroring

```bash
Run shogo82148/actions-cfn-lint@v1.6.15-beta3
  with:
    github_token: ***
    cfn_lint_args: --config-file .cfnlintrc
    level: error
    tool_name: cfn-lint
    reporter: github-pr-check
    filter_mode: added
    fail_on_error: false
...
2021-02-22 07:45:42,176 - cfnlint.decode - ERROR - Template file not found: None
reviewdog: failed to run 'git rev-parse --show-prefix': exit status 128
```

**Comment by shogo82148** [comment]
Can I have the whole of your workflow YAML file and logs, please?

**Comment by jmeridth** [comment]
`.github/workflows/pullRequest.yml`

```yaml
name: Pull Request
on:
  pull_request:

jobs:
  Lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Cloudformation template linting
        uses: shogo82148/actions-cfn-lint@v1.6.15-beta3
        with:
          github_token: ${{ secrets.REDACTED_TOKEN_KEY }}
          cfn_lint_args: --config-file .cfnlintrc
```

`.cfnlintrc`

```
templates:
  - "**/*.yaml"
  - "*.json"
  
```

LOGS

```bash
Run shogo82148/actions-cfn-lint@v1.6.15-beta3
  with:
    github_token: ***
    cfn_lint_args: --config-file .cfnlintrc
    level: error
    tool_name: cfn-lint
    reporter: github-pr-check
    filter_mode: added
    fail_on_error: false
/usr/bin/docker run --name shogo82148actionscfnlint1615beta3_b4deb5 --label 5588e4 --workdir /github/workspace --rm -e INPUT_GITHUB_TOKEN -e INPUT_CFN_LINT_ARGS -e INPUT_LEVEL -e INPUT_TOOL_NAME -e INPUT_REPORTER -e INPUT_FILTER_MODE -e INPUT_FAIL_ON_ERROR -e INPUT_REVIEWDOG_FLAGS -e HOME -e GITHUB_JOB -e GITHUB_REF -e GITHUB_SHA -e GITHUB_REPOSITORY -e GITHUB_REPOSITORY_OWNER -e GITHUB_RUN_ID -e GITHUB_RUN_NUMBER -e GITHUB_RETENTION_DAYS -e GITHUB_ACTOR -e GITHUB_WORKFLOW -e GITHUB_HEAD_REF -e GITHUB_BASE_REF -e GITHUB_EVENT_NAME -e GITHUB_SERVER_URL -e GITHUB_API_URL -e GITHUB_GRAPHQL_URL -e GITHUB_WORKSPACE -e GITHUB_ACTION -e GITHUB_EVENT_PATH -e GITHUB_ACTION_REPOSITORY -e GITHUB_ACTION_REF -e GITHUB_PATH -e GITHUB_ENV -e RUNNER_OS -e RUNNER_TOOL_CACHE -e RUNNER_TEMP -e RUNNER_WORKSPACE -e ACTIONS_RUNTIME_URL -e ACTIONS_RUNTIME_TOKEN -e ACTIONS_CACHE_URL -e GITHUB_ACTIONS=true -e CI=true -v "/var/run/docker.sock":"/var/run/docker.sock" -v "/home/runner/work/_temp/_github_home":"/github/home" -v "/home/runner/work/_temp/_github_workflow":"/github/workflow" -v "/home/runner/work/_temp/_runner_file_commands":"/github/file_commands" -v "/home/runner/work/REDACTED_REPO_NAME/REDACTED_REPO_NAME":"/github/workspace" shogo82148/actions-cfn-lint:1.6.15-beta3  "**/*.yaml" "**/*.yml" "**/*.json"
2021-02-22 07:45:42,176 - cfnlint.decode - ERROR - Template file not found: None
reviewdog: failed to run 'git rev-parse --show-prefix': exit status 128
```

**Comment by shogo82148** [comment]
That's whole?

You need to add `uses: actions/checkout@v2` step before the `uses: shogo82148/actions-cfn-lint@v1.6.15-beta3`.
actions-cfn-lint doesn't checkout the repository.

**Comment by jmeridth** [comment]
@shogo82148 that was it.  /me slaps forehead.  Feel kind of dumb right now.  😄 

Now it runs but I'm getting

```bash
Run shogo82148/actions-cfn-lint@v1.6.15-beta3
  with:
    github_token: ***
    cfn_lint_args: --config-file .cfnlintrc
    level: error
    tool_name: cfn-lint
    reporter: github-pr-check
    filter_mode: added
    fail_on_error: false
/usr/bin/docker run --name shogo82148actionscfnlint1615beta3_b55ca0 --label 5588e4 --workdir /github/workspace --rm -e INPUT_GITHUB_TOKEN -e INPUT_CFN_LINT_ARGS -e INPUT_LEVEL -e INPUT_TOOL_NAME -e INPUT_REPORTER -e INPUT_FILTER_MODE -e INPUT_FAIL_ON_ERROR -e INPUT_REVIEWDOG_FLAGS -e HOME -e GITHUB_JOB -e GITHUB_REF -e GITHUB_SHA -e GITHUB_REPOSITORY -e GITHUB_REPOSITORY_OWNER -e GITHUB_RUN_ID -e GITHUB_RUN_NUMBER -e GITHUB_RETENTION_DAYS -e GITHUB_ACTOR -e GITHUB_WORKFLOW -e GITHUB_HEAD_REF -e GITHUB_BASE_REF -e GITHUB_EVENT_NAME -e GITHUB_SERVER_URL -e GITHUB_API_URL -e GITHUB_GRAPHQL_URL -e GITHUB_WORKSPACE -e GITHUB_ACTION -e GITHUB_EVENT_PATH -e GITHUB_ACTION_REPOSITORY -e GITHUB_ACTION_REF -e GITHUB_PATH -e GITHUB_ENV -e RUNNER_OS -e RUNNER_TOOL_CACHE -e RUNNER_TEMP -e RUNNER_WORKSPACE -e ACTIONS_RUNTIME_URL -e ACTIONS_RUNTIME_TOKEN -e ACTIONS_CACHE_URL -e GITHUB_ACTIONS=true -e CI=true -v "/var/run/docker.sock":"/var/run/docker.sock" -v "/home/runner/work/_temp/_github_home":"/github/home" -v "/home/runner/work/_temp/_github_workflow":"/github/workflow" -v "/home/runner/work/_temp/_runner_file_commands":"/github/file_commands" -v "/home/runner/work/REDACTED_REPO_NAME/REDACTED_REPO_NAME":"/github/workspace" shogo82148/actions-cfn-lint:1.6.15-beta3  "**/*.yaml" "**/*.yml" "**/*.json"
reviewdog: Reporting results for "cfn-lint"
reviewdog: No results found for "cfn-lint". 259 results found outside diff.
```

Am I missing something?

```yaml
name: Pull Request
on:
  pull_request:

jobs:
  Lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v2
      - name: Cloudformation template linting
        uses: shogo82148/actions-cfn-lint@v1.6.15-beta3
        with:
          github_token: ${{ secrets.REDACTED_KEY_NAME }}
          cfn_lint_args: --config-file .cfnlintrc
```

**Comment by shogo82148** [comment]
It works well.

reviewdog reports lint warnings related with the pull request.
I guess that your templates files have no changes in the pull request.
In this case, reviewdog reports nothing.

please try to add some resources into your template.

**Comment by jmeridth** [comment]
Ah, gotcha. Will test.  Cheers.

**Comment by jmeridth** [comment]
Ok. You can close this issue.  I'm still trying to figure out the sequence where I can see all the linting errors in the entire repo outside the context of the PR but not have them error (only warn).  May not be able to happen with `cfn-lint`.  Thank you so much for your help on this.
